### ISSUE TITLE
Error getting rss data

### ISSUE THREAD

**Issue by michael-stevens** [lambdaq/munin-uwsgi-stats#3]
Hi,

I tried to use this as uwsgi_rss to get rss data, but I get:

```
2016/03/07-11:20:42 [9349] Error output from uwsgi_rss:
2016/03/07-11:20:42 [9349]      Traceback (most recent call last):
2016/03/07-11:20:42 [9349]        File "/etc/munin/plugins/uwsgi_rss", line 124, in <module>
2016/03/07-11:20:42 [9349]          get_uwsgi_processes(apps)
2016/03/07-11:20:42 [9349]        File "/etc/munin/plugins/uwsgi_rss", line 85, in get_uwsgi_processes
2016/03/07-11:20:42 [9349]          if p.cmdline[0] == 'uWSGI master':
2016/03/07-11:20:42 [9349]      TypeError: 'instancemethod' object is unsubscriptable
2016/03/07-11:20:42 [9349] Service 'uwsgi_rss' exited with status 1/0.
```

**Comment by lambdaq** [comment]
`p.cmdline` is a function. Ahhh.

I don't use munin anymore so I don't have the proper env to debug it sorry.
